services:
  webapi:
    build: 
      context: Students
      dockerfile: ChatRoom/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      TZ: Asia/Bangkok
      
  nginx:
    image: nginx:1.27-bookworm
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
    environment:
      TZ: Asia/Bangkok